<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Buku_model extends CI_Model
{

    public $view = 'v_buku';
    public $table = 'tb_buku';
    public $id = 'id_buku';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_view()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->view)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_buku', $q);
	$this->db->or_like('id_rak', $q);
	$this->db->or_like('id_penerbit', $q);
	$this->db->or_like('nm_buku', $q);
	$this->db->or_like('thn_terbit', $q);
	$this->db->or_like('nm_penulis', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_buku', $q);
	$this->db->or_like('id_rak', $q);
	$this->db->or_like('id_penerbit', $q);
	$this->db->or_like('nm_buku', $q);
	$this->db->or_like('thn_terbit', $q);
	$this->db->or_like('nm_penulis', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Buku_model.php */
/* Location: ./application/models/Buku_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-14 13:15:50 */
/* http://harviacode.com */
