<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kariawan_model extends CI_Model
{

    public $table = 'tb_kariawan';
    public $id = 'nik';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('nik', $q);
      	$this->db->or_like('nama', $q);
      	$this->db->or_like('jen_kel', $q);
      	$this->db->or_like('tmp_lahir', $q);
      	$this->db->or_like('tgl_lahir', $q);
      	$this->db->or_like('agama', $q);
      	$this->db->or_like('jabatan', $q);
      	$this->db->or_like('alamat', $q);
      	$this->db->or_like('no_hp', $q);
      	$this->db->or_like('email', $q);
      	$this->db->or_like('s1_nm_sklh', $q);
      	$this->db->or_like('s1_jur', $q);
      	$this->db->or_like('s1_thn_lulus', $q);
      	$this->db->or_like('s1_kota', $q);
      	$this->db->or_like('s2_nm_sklh', $q);
      	$this->db->or_like('s2_jur', $q);
      	$this->db->or_like('s2_thn_lulus', $q);
      	$this->db->or_like('s2_kota', $q);
      	$this->db->or_like('s3_nm_sklh', $q);
      	$this->db->or_like('s3_jur', $q);
      	$this->db->or_like('s3_thn_lulus', $q);
      	$this->db->or_like('s3_kota', $q);
      	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jen_kel', $q);
	$this->db->or_like('tmp_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('s1_nm_sklh', $q);
	$this->db->or_like('s1_jur', $q);
	$this->db->or_like('s1_thn_lulus', $q);
	$this->db->or_like('s1_kota', $q);
	$this->db->or_like('s2_nm_sklh', $q);
	$this->db->or_like('s2_jur', $q);
	$this->db->or_like('s2_thn_lulus', $q);
	$this->db->or_like('s2_kota', $q);
	$this->db->or_like('s3_nm_sklh', $q);
	$this->db->or_like('s3_jur', $q);
	$this->db->or_like('s3_thn_lulus', $q);
	$this->db->or_like('s3_kota', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kariawan_model.php */
/* Location: ./application/models/Kariawan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-09 21:38:35 */
/* http://harviacode.com */
