<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Setting_model extends CI_Model
{

    public $table = 'tb_setting';
    public $id = 'id_sett';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_sett', $q);
	$this->db->or_like('kode_feed', $q);
	$this->db->or_like('pass_feed', $q);
	$this->db->or_like('role', $q);
	$this->db->or_like('url_ws', $q);
	$this->db->or_like('mode', $q);
	$this->db->or_like('link', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sett', $q);
	$this->db->or_like('kode_feed', $q);
	$this->db->or_like('pass_feed', $q);
	$this->db->or_like('role', $q);
	$this->db->or_like('url_ws', $q);
	$this->db->or_like('mode', $q);
	$this->db->or_like('link', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Setting_model.php */
/* Location: ./application/models/Setting_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-09 21:46:57 */
/* http://harviacode.com */